#!/usr/local/bin/node

// utility script  returns paragraph from Wikipedia link, stripped of reference numbers.
// take url as commandline arg

let request = require("request");
let url = process.argv[2];

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

request(url, function (error, response, body) {
  // Simulate a Document Object Model
  let { document } = (new JSDOM(body)).window;

  // Grab all paragraphs and references
  let paragraphs = document.querySelectorAll("p");
  let references = document.querySelectorAll(".reference");

  // Remove any references
  references.forEach(function(reference){
    reference.remove();
  });

  // Print all paragraphs
  paragraphs.forEach(function(paragraph){
    console.log(paragraph.textContent);
  });
});
